// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadiologyCenter.Identity.Infrastructure.Persistence;

#nullable disable

namespace RadiologyCenter.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260808144310_AddInsurancePermissions")]
    partial class AddInsurancePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.Property<Guid>("AssignedRolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignedRolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AspNetPermissions", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e217b13-4ae0-c10c-1621-73cd73ed24e5"),
                            Code = "patients.create",
                            Description = "Create new patient records",
                            Group = "Patients",
                            Name = "Create Patients"
                        },
                        new
                        {
                            Id = new Guid("65723bc4-bc7f-cfc2-e1bc-c73ccb86d023"),
                            Code = "patients.read",
                            Description = "View patient records",
                            Group = "Patients",
                            Name = "Read Patients"
                        },
                        new
                        {
                            Id = new Guid("1ae22bb0-fb7f-0935-840d-f9e4061824c5"),
                            Code = "patients.update",
                            Description = "Modify existing patient records",
                            Group = "Patients",
                            Name = "Update Patients"
                        },
                        new
                        {
                            Id = new Guid("1ceb83f1-b049-1e41-e030-ca764a191d37"),
                            Code = "patients.delete",
                            Description = "Remove patient records",
                            Group = "Patients",
                            Name = "Delete Patients"
                        },
                        new
                        {
                            Id = new Guid("56038185-f0f0-7c61-21cf-3d56d86c9e7b"),
                            Code = "appointments.create",
                            Description = "Schedule new appointments",
                            Group = "Appointments",
                            Name = "Create Appointments"
                        },
                        new
                        {
                            Id = new Guid("97f0ba16-636a-f3d1-38b5-aa196fda0fe6"),
                            Code = "appointments.read",
                            Description = "View appointment details",
                            Group = "Appointments",
                            Name = "Read Appointments"
                        },
                        new
                        {
                            Id = new Guid("4574d456-6962-ee5d-f344-7c87735df7a9"),
                            Code = "appointments.update",
                            Description = "Modify existing appointments",
                            Group = "Appointments",
                            Name = "Update Appointments"
                        },
                        new
                        {
                            Id = new Guid("00ff18fa-d4d9-c572-efd3-9c608735129c"),
                            Code = "appointments.delete",
                            Description = "Cancel or remove appointments",
                            Group = "Appointments",
                            Name = "Delete Appointments"
                        },
                        new
                        {
                            Id = new Guid("8b825d03-711b-92c8-9d04-999b294a318c"),
                            Code = "appointments.confirm",
                            Description = "Confirm scheduled appointments",
                            Group = "Appointments",
                            Name = "Confirm Appointments"
                        },
                        new
                        {
                            Id = new Guid("88074e00-d501-1516-74f1-359b42bb70b5"),
                            Code = "reports.create",
                            Description = "Generate new radiology reports",
                            Group = "Reports",
                            Name = "Create Reports"
                        },
                        new
                        {
                            Id = new Guid("121e49c3-044e-461a-62be-f488d70e32a5"),
                            Code = "reports.read",
                            Description = "View radiology reports",
                            Group = "Reports",
                            Name = "Read Reports"
                        },
                        new
                        {
                            Id = new Guid("afb3c764-ed7b-76fb-d661-bb52f1632f24"),
                            Code = "reports.update",
                            Description = "Modify existing reports",
                            Group = "Reports",
                            Name = "Update Reports"
                        },
                        new
                        {
                            Id = new Guid("a9b6b892-9cbf-5e0d-524e-342037a9c0db"),
                            Code = "reports.delete",
                            Description = "Remove reports",
                            Group = "Reports",
                            Name = "Delete Reports"
                        },
                        new
                        {
                            Id = new Guid("4cdd0e15-99f2-163d-bf02-7f9c7085639b"),
                            Code = "reports.export",
                            Description = "Export reports to external formats",
                            Group = "Reports",
                            Name = "Export Reports"
                        },
                        new
                        {
                            Id = new Guid("ddb0acbe-d395-bda1-dff1-b254d37718bc"),
                            Code = "analytics.read",
                            Description = "View analytics and business intelligence dashboards",
                            Group = "Analytics",
                            Name = "Read Analytics"
                        },
                        new
                        {
                            Id = new Guid("5e7b27cf-8d84-9117-ace6-bf62930c0d6b"),
                            Code = "users.create",
                            Description = "Create new user accounts",
                            Group = "Identity",
                            Name = "Create Users"
                        },
                        new
                        {
                            Id = new Guid("39599987-0f11-0d0a-d879-7cbd0644220f"),
                            Code = "users.read",
                            Description = "View user accounts",
                            Group = "Identity",
                            Name = "Read Users"
                        },
                        new
                        {
                            Id = new Guid("9357da48-43eb-8b5a-08e1-2970f32cd4e4"),
                            Code = "users.update",
                            Description = "Modify user accounts",
                            Group = "Identity",
                            Name = "Update Users"
                        },
                        new
                        {
                            Id = new Guid("4f1937b2-d2ab-81d3-231f-fd3f82eaeee9"),
                            Code = "users.delete",
                            Description = "Remove user accounts",
                            Group = "Identity",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = new Guid("34aefeb7-996c-2279-4a5f-a07ee459a73d"),
                            Code = "users.manage-roles",
                            Description = "Assign or remove roles from users",
                            Group = "Identity",
                            Name = "Manage User Roles"
                        },
                        new
                        {
                            Id = new Guid("75a5654b-9b89-dd90-0386-c2bf38eb1fa7"),
                            Code = "roles.create",
                            Description = "Create new roles",
                            Group = "Identity",
                            Name = "Create Roles"
                        },
                        new
                        {
                            Id = new Guid("5ca0bded-ae70-5972-59c3-7541f4dae0c5"),
                            Code = "roles.read",
                            Description = "View roles",
                            Group = "Identity",
                            Name = "Read Roles"
                        },
                        new
                        {
                            Id = new Guid("3bcb99ff-db6c-7983-9afd-e23a514b8d87"),
                            Code = "roles.update",
                            Description = "Modify role details",
                            Group = "Identity",
                            Name = "Update Roles"
                        },
                        new
                        {
                            Id = new Guid("8e5a0684-bcd2-8840-b701-2312fcb7ecfa"),
                            Code = "roles.delete",
                            Description = "Remove roles",
                            Group = "Identity",
                            Name = "Delete Roles"
                        },
                        new
                        {
                            Id = new Guid("e66a4a79-01e6-8e89-c8c5-d0ce5044fa01"),
                            Code = "roles.manage-permissions",
                            Description = "Assign or remove permissions from roles",
                            Group = "Identity",
                            Name = "Manage Role Permissions"
                        },
                        new
                        {
                            Id = new Guid("0c592871-6663-c321-024b-f782e8aa258f"),
                            Code = "settings.read",
                            Description = "View system settings",
                            Group = "Settings",
                            Name = "Read Settings"
                        },
                        new
                        {
                            Id = new Guid("e0548f02-0b69-0aa7-d0c3-6b4f5b7a69dd"),
                            Code = "settings.update",
                            Description = "Modify system settings",
                            Group = "Settings",
                            Name = "Update Settings"
                        },
                        new
                        {
                            Id = new Guid("0f5f7960-ff37-1d18-b8db-a247701c15aa"),
                            Code = "inventory.items.create",
                            Description = "Add new inventory items",
                            Group = "Inventory",
                            Name = "Create Inventory Items"
                        },
                        new
                        {
                            Id = new Guid("faac6b2a-dca3-cef4-efd0-20060a4de1e4"),
                            Code = "inventory.items.read",
                            Description = "View inventory items",
                            Group = "Inventory",
                            Name = "Read Inventory Items"
                        },
                        new
                        {
                            Id = new Guid("4933b20c-0e69-2b2a-afcc-9160c5d28e84"),
                            Code = "inventory.items.update",
                            Description = "Modify inventory items",
                            Group = "Inventory",
                            Name = "Update Inventory Items"
                        },
                        new
                        {
                            Id = new Guid("4905eb25-4c3b-fee3-c118-fb8437c960f2"),
                            Code = "inventory.items.delete",
                            Description = "Remove inventory items",
                            Group = "Inventory",
                            Name = "Delete Inventory Items"
                        },
                        new
                        {
                            Id = new Guid("102e0a19-9c61-a973-203c-a2216fa0fca2"),
                            Code = "inventory.suppliers.create",
                            Description = "Add new suppliers",
                            Group = "Inventory",
                            Name = "Create Inventory Suppliers"
                        },
                        new
                        {
                            Id = new Guid("b079ac2e-ee45-24cf-fc5d-26ecff766e16"),
                            Code = "inventory.suppliers.read",
                            Description = "View suppliers",
                            Group = "Inventory",
                            Name = "Read Inventory Suppliers"
                        },
                        new
                        {
                            Id = new Guid("ab653fcc-50eb-0af8-5aaf-16e746bb5385"),
                            Code = "inventory.suppliers.update",
                            Description = "Modify suppliers",
                            Group = "Inventory",
                            Name = "Update Inventory Suppliers"
                        },
                        new
                        {
                            Id = new Guid("b370e3e6-f655-f445-ee3c-e3fbd74e489a"),
                            Code = "inventory.suppliers.delete",
                            Description = "Remove suppliers",
                            Group = "Inventory",
                            Name = "Delete Inventory Suppliers"
                        },
                        new
                        {
                            Id = new Guid("df6c1ff4-ee40-8ae2-df55-166358e7bdcb"),
                            Code = "inventory.purchase-orders.create",
                            Description = "Create purchase orders",
                            Group = "Inventory",
                            Name = "Create Purchase Orders"
                        },
                        new
                        {
                            Id = new Guid("fe88b74c-0e4d-4306-e2c1-961f38291ea0"),
                            Code = "inventory.purchase-orders.read",
                            Description = "View purchase orders",
                            Group = "Inventory",
                            Name = "Read Purchase Orders"
                        },
                        new
                        {
                            Id = new Guid("32374a33-3ce6-2306-9c99-97e5d4a55398"),
                            Code = "inventory.purchase-orders.update",
                            Description = "Modify purchase orders",
                            Group = "Inventory",
                            Name = "Update Purchase Orders"
                        },
                        new
                        {
                            Id = new Guid("98f262b3-ca68-3bba-a914-f98d3e4947e5"),
                            Code = "inventory.purchase-orders.delete",
                            Description = "Remove purchase orders",
                            Group = "Inventory",
                            Name = "Delete Purchase Orders"
                        },
                        new
                        {
                            Id = new Guid("e6f1e4d7-92ab-2021-daab-ee4841a4e5e2"),
                            Code = "inventory.stock.read",
                            Description = "View stock levels and movements",
                            Group = "Inventory",
                            Name = "Read Stock"
                        },
                        new
                        {
                            Id = new Guid("2d3098d7-c9a9-5764-17d5-15b4f1ccf0a2"),
                            Code = "inventory.stock.issue",
                            Description = "Issue stock to patients",
                            Group = "Inventory",
                            Name = "Issue Stock"
                        },
                        new
                        {
                            Id = new Guid("3df9de9b-0161-716c-2495-11ca6fe3bfe6"),
                            Code = "examinations.types.manage",
                            Description = "Create, update, delete and activate examination types",
                            Group = "Examinations",
                            Name = "Manage Examination Types"
                        },
                        new
                        {
                            Id = new Guid("14f46857-9a94-9ca0-67ec-54a34f8b4ee7"),
                            Code = "examinations.create",
                            Description = "Create visits and add examinations",
                            Group = "Examinations",
                            Name = "Create Examinations"
                        },
                        new
                        {
                            Id = new Guid("c5ad4ec4-37cb-8d65-1f99-893d6fa9171b"),
                            Code = "examinations.read",
                            Description = "View visits and examinations",
                            Group = "Examinations",
                            Name = "Read Examinations"
                        },
                        new
                        {
                            Id = new Guid("c767d3a2-dd4b-0c1b-00b0-d99ea2bfbbc8"),
                            Code = "examinations.update",
                            Description = "Modify examinations and their items",
                            Group = "Examinations",
                            Name = "Update Examinations"
                        },
                        new
                        {
                            Id = new Guid("66a83501-5f9a-542f-9599-fc724b3f81e6"),
                            Code = "examinations.delete",
                            Description = "Remove examinations",
                            Group = "Examinations",
                            Name = "Delete Examinations"
                        },
                        new
                        {
                            Id = new Guid("0e0e01dc-293a-3acb-4dd7-7a8f251916d8"),
                            Code = "examinations.perform",
                            Description = "Start and complete examinations",
                            Group = "Examinations",
                            Name = "Perform Examinations"
                        },
                        new
                        {
                            Id = new Guid("dd84e7dd-c45f-4441-6c18-4deb65b3830c"),
                            Code = "examinations.cancel",
                            Description = "Cancel visits and examinations",
                            Group = "Examinations",
                            Name = "Cancel Examinations"
                        },
                        new
                        {
                            Id = new Guid("d8a19a08-1c83-5859-0163-7ce116ccbf1d"),
                            Code = "resources.staff.create",
                            Description = "Add new staff members",
                            Group = "Resources",
                            Name = "Create Staff"
                        },
                        new
                        {
                            Id = new Guid("b621ec27-1a85-5071-31d6-c48d94fdc07e"),
                            Code = "resources.staff.read",
                            Description = "View staff members",
                            Group = "Resources",
                            Name = "Read Staff"
                        },
                        new
                        {
                            Id = new Guid("faf46329-5963-eb14-13e3-957757d84b62"),
                            Code = "resources.staff.update",
                            Description = "Modify staff members",
                            Group = "Resources",
                            Name = "Update Staff"
                        },
                        new
                        {
                            Id = new Guid("4ff54837-8f20-a8b5-93aa-5c626742a079"),
                            Code = "resources.staff.delete",
                            Description = "Remove staff members",
                            Group = "Resources",
                            Name = "Delete Staff"
                        },
                        new
                        {
                            Id = new Guid("a15b39d5-580d-d2bc-109e-d2dcdfbfabaa"),
                            Code = "resources.equipment.create",
                            Description = "Add new equipment",
                            Group = "Resources",
                            Name = "Create Equipment"
                        },
                        new
                        {
                            Id = new Guid("26a1fa35-132a-d4a3-90ca-ba0fc0a78a39"),
                            Code = "resources.equipment.read",
                            Description = "View equipment",
                            Group = "Resources",
                            Name = "Read Equipment"
                        },
                        new
                        {
                            Id = new Guid("c09e4f7a-1fca-53f3-36bc-a16070f6e2cd"),
                            Code = "resources.equipment.update",
                            Description = "Modify equipment and its status",
                            Group = "Resources",
                            Name = "Update Equipment"
                        },
                        new
                        {
                            Id = new Guid("d34aa12a-13ac-fb27-68a7-2a8fcaf070dd"),
                            Code = "resources.equipment.delete",
                            Description = "Remove equipment",
                            Group = "Resources",
                            Name = "Delete Equipment"
                        },
                        new
                        {
                            Id = new Guid("891ac850-50b8-c0fd-75d4-72f57935a9cf"),
                            Code = "resources.shifts.create",
                            Description = "Add new work shifts",
                            Group = "Resources",
                            Name = "Create Work Shifts"
                        },
                        new
                        {
                            Id = new Guid("4b4bcccb-78a8-9410-5fa2-0b2b5ad02b2e"),
                            Code = "resources.shifts.read",
                            Description = "View work shifts",
                            Group = "Resources",
                            Name = "Read Work Shifts"
                        },
                        new
                        {
                            Id = new Guid("402f63c9-2c76-0acc-6e19-d80c01fe35d2"),
                            Code = "resources.shifts.update",
                            Description = "Modify work shifts",
                            Group = "Resources",
                            Name = "Update Work Shifts"
                        },
                        new
                        {
                            Id = new Guid("80dcaed2-5408-90c5-33ed-a0bad9c12f73"),
                            Code = "resources.shifts.delete",
                            Description = "Remove work shifts",
                            Group = "Resources",
                            Name = "Delete Work Shifts"
                        },
                        new
                        {
                            Id = new Guid("90420a38-f060-a86e-fb75-ca18548d1331"),
                            Code = "resources.leave.create",
                            Description = "Add new leave records",
                            Group = "Resources",
                            Name = "Create Leave"
                        },
                        new
                        {
                            Id = new Guid("f3b4c0c6-ed22-c0e9-bb34-df2f3fb348a1"),
                            Code = "resources.leave.read",
                            Description = "View leave records",
                            Group = "Resources",
                            Name = "Read Leave"
                        },
                        new
                        {
                            Id = new Guid("9cd729b1-31ce-5e23-0590-ec97a7b105d5"),
                            Code = "resources.leave.update",
                            Description = "Modify leave records",
                            Group = "Resources",
                            Name = "Update Leave"
                        },
                        new
                        {
                            Id = new Guid("fd9f1ca5-ef9b-f26a-a228-8ab82baf9b5d"),
                            Code = "resources.leave.delete",
                            Description = "Remove leave records",
                            Group = "Resources",
                            Name = "Delete Leave"
                        },
                        new
                        {
                            Id = new Guid("805ea172-9edb-bb9b-3fdd-fde364ecbe07"),
                            Code = "resources.referrals.create",
                            Description = "Add new referral doctors",
                            Group = "Resources",
                            Name = "Create Referral Doctors"
                        },
                        new
                        {
                            Id = new Guid("7415bdf8-1d07-18a7-136e-0d08cd337e2c"),
                            Code = "resources.referrals.read",
                            Description = "View referral doctors",
                            Group = "Resources",
                            Name = "Read Referral Doctors"
                        },
                        new
                        {
                            Id = new Guid("a9e36669-7b2a-d91f-10ca-d5899b40d9c9"),
                            Code = "resources.referrals.update",
                            Description = "Modify referral doctors",
                            Group = "Resources",
                            Name = "Update Referral Doctors"
                        },
                        new
                        {
                            Id = new Guid("e0083532-de12-5242-d6db-6ecf4cc91719"),
                            Code = "resources.referrals.delete",
                            Description = "Remove referral doctors",
                            Group = "Resources",
                            Name = "Delete Referral Doctors"
                        },
                        new
                        {
                            Id = new Guid("41fefb26-f3c2-e784-4c76-890dee36e6eb"),
                            Code = "payroll.read",
                            Description = "View payroll records",
                            Group = "Payroll",
                            Name = "Read Payroll"
                        },
                        new
                        {
                            Id = new Guid("af121ffb-79e2-804a-901f-97c3c40b0c9a"),
                            Code = "payroll.salary-components.manage",
                            Description = "Create, update, activate and delete salary components",
                            Group = "Payroll",
                            Name = "Manage Salary Components"
                        },
                        new
                        {
                            Id = new Guid("5999b9cd-e387-2bb4-0fe6-ddaa9e133ee7"),
                            Code = "payroll.salary.manage",
                            Description = "Create, update, activate and delete staff salaries",
                            Group = "Payroll",
                            Name = "Manage Salaries"
                        },
                        new
                        {
                            Id = new Guid("ecb71584-005e-bc07-3cea-0e99b44ce6b5"),
                            Code = "payroll.allowances.manage",
                            Description = "Create, update, activate and delete allowance assignments",
                            Group = "Payroll",
                            Name = "Manage Allowances"
                        },
                        new
                        {
                            Id = new Guid("9a611184-7476-b59a-382c-5918515fc4bd"),
                            Code = "payroll.fees.manage",
                            Description = "Create, update, activate and delete examination and referral fees",
                            Group = "Payroll",
                            Name = "Manage Payroll Fees"
                        },
                        new
                        {
                            Id = new Guid("7fd2558b-b5b3-6988-0f52-a4330c5717f2"),
                            Code = "payroll.payruns.manage",
                            Description = "Create pay runs and manage their payslips",
                            Group = "Payroll",
                            Name = "Manage Pay Runs"
                        },
                        new
                        {
                            Id = new Guid("163a203a-e0e1-db23-f09c-702f14888def"),
                            Code = "payroll.payruns.run",
                            Description = "Compute, approve, reject and pay pay runs",
                            Group = "Payroll",
                            Name = "Run Pay Rolls"
                        },
                        new
                        {
                            Id = new Guid("d6f95542-491f-0bf6-8ad1-61e153ada390"),
                            Code = "insurance.companies.create",
                            Description = "Add new insurance companies",
                            Group = "Insurance",
                            Name = "Create Insurance Companies"
                        },
                        new
                        {
                            Id = new Guid("132122fc-1997-a6d7-3a26-73321a222012"),
                            Code = "insurance.companies.read",
                            Description = "View insurance companies",
                            Group = "Insurance",
                            Name = "Read Insurance Companies"
                        },
                        new
                        {
                            Id = new Guid("7246f9e5-5290-a93d-94fd-de8ea1155658"),
                            Code = "insurance.companies.update",
                            Description = "Modify insurance company details",
                            Group = "Insurance",
                            Name = "Update Insurance Companies"
                        },
                        new
                        {
                            Id = new Guid("5dcfa2a7-f105-26de-b69d-1f77f4bd146c"),
                            Code = "insurance.companies.delete",
                            Description = "Remove insurance companies",
                            Group = "Insurance",
                            Name = "Delete Insurance Companies"
                        },
                        new
                        {
                            Id = new Guid("ff6e49ff-a8bd-f63b-10b9-f3c6b96d55d2"),
                            Code = "insurance.policies.create",
                            Description = "Add new patient insurance policies",
                            Group = "Insurance",
                            Name = "Create Insurance Policies"
                        },
                        new
                        {
                            Id = new Guid("1b0affa6-08cf-6c02-f07b-4e4e581b2acb"),
                            Code = "insurance.policies.read",
                            Description = "View patient insurance policies",
                            Group = "Insurance",
                            Name = "Read Insurance Policies"
                        },
                        new
                        {
                            Id = new Guid("467e6cd7-0231-2549-cdb2-81fe748d1181"),
                            Code = "insurance.policies.update",
                            Description = "Modify policies, coverage and status",
                            Group = "Insurance",
                            Name = "Update Insurance Policies"
                        },
                        new
                        {
                            Id = new Guid("0d0decde-1413-1cd1-5b0e-a10491ee5cab"),
                            Code = "insurance.policies.delete",
                            Description = "Remove insurance policies",
                            Group = "Insurance",
                            Name = "Delete Insurance Policies"
                        },
                        new
                        {
                            Id = new Guid("87502c83-12b4-29a2-cbed-1ee184a9ff3c"),
                            Code = "insurance.preauthorizations.create",
                            Description = "Request pre-authorization for examinations",
                            Group = "Insurance",
                            Name = "Create Pre-authorizations"
                        },
                        new
                        {
                            Id = new Guid("5441cf09-ce40-6b0f-5e79-bd3b26e88e33"),
                            Code = "insurance.preauthorizations.read",
                            Description = "View pre-authorizations and documents",
                            Group = "Insurance",
                            Name = "Read Pre-authorizations"
                        },
                        new
                        {
                            Id = new Guid("5a6d94df-7ddf-4379-8bb2-6484890a47bc"),
                            Code = "insurance.preauthorizations.update",
                            Description = "Approve, deny or attach documents",
                            Group = "Insurance",
                            Name = "Update Pre-authorizations"
                        },
                        new
                        {
                            Id = new Guid("8f39be78-ecee-6ac8-8720-a47d11f2f6c9"),
                            Code = "insurance.preauthorizations.attach-document",
                            Description = "Upload or remove official approval documents",
                            Group = "Insurance",
                            Name = "Attach Pre-authorization Documents"
                        },
                        new
                        {
                            Id = new Guid("2fd73645-e204-fd4c-34fb-d406faf0b826"),
                            Code = "insurance.claims.create",
                            Description = "Create claims for covered examinations",
                            Group = "Insurance",
                            Name = "Create Claims"
                        },
                        new
                        {
                            Id = new Guid("1cd6d7c7-54ef-0ef8-a571-2ce54c289db8"),
                            Code = "insurance.claims.read",
                            Description = "View claims and their lifecycle",
                            Group = "Insurance",
                            Name = "Read Claims"
                        },
                        new
                        {
                            Id = new Guid("d8a7d18a-9676-f315-26d9-4e4d30c408d6"),
                            Code = "insurance.claims.update",
                            Description = "Submit, resubmit and adjudicate claims",
                            Group = "Insurance",
                            Name = "Update Claims"
                        },
                        new
                        {
                            Id = new Guid("74d81d37-dad6-4cc5-d480-e208dbcd9419"),
                            Code = "insurance.claims.settle",
                            Description = "Record insurance settlements",
                            Group = "Insurance",
                            Name = "Settle Claims"
                        });
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", "Identity");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "Identity");
                });

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("AssignedRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsMany("RadiologyCenter.Identity.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Token")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("UserId", "Token");

                            b1.ToTable("RefreshToken", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
