// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadiologyCenter.Identity.Infrastructure.Persistence;

#nullable disable

namespace RadiologyCenter.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.Property<Guid>("AssignedRolesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AssignedRolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AspNetPermissions", "Identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e217b13-4ae0-c10c-1621-73cd73ed24e5"),
                            Code = "patients.create",
                            Description = "Create new patient records",
                            Group = "Patients",
                            Name = "Create Patients"
                        },
                        new
                        {
                            Id = new Guid("65723bc4-bc7f-cfc2-e1bc-c73ccb86d023"),
                            Code = "patients.read",
                            Description = "View patient records",
                            Group = "Patients",
                            Name = "Read Patients"
                        },
                        new
                        {
                            Id = new Guid("1ae22bb0-fb7f-0935-840d-f9e4061824c5"),
                            Code = "patients.update",
                            Description = "Modify existing patient records",
                            Group = "Patients",
                            Name = "Update Patients"
                        },
                        new
                        {
                            Id = new Guid("1ceb83f1-b049-1e41-e030-ca764a191d37"),
                            Code = "patients.delete",
                            Description = "Remove patient records",
                            Group = "Patients",
                            Name = "Delete Patients"
                        },
                        new
                        {
                            Id = new Guid("56038185-f0f0-7c61-21cf-3d56d86c9e7b"),
                            Code = "appointments.create",
                            Description = "Schedule new appointments",
                            Group = "Appointments",
                            Name = "Create Appointments"
                        },
                        new
                        {
                            Id = new Guid("97f0ba16-636a-f3d1-38b5-aa196fda0fe6"),
                            Code = "appointments.read",
                            Description = "View appointment details",
                            Group = "Appointments",
                            Name = "Read Appointments"
                        },
                        new
                        {
                            Id = new Guid("4574d456-6962-ee5d-f344-7c87735df7a9"),
                            Code = "appointments.update",
                            Description = "Modify existing appointments",
                            Group = "Appointments",
                            Name = "Update Appointments"
                        },
                        new
                        {
                            Id = new Guid("00ff18fa-d4d9-c572-efd3-9c608735129c"),
                            Code = "appointments.delete",
                            Description = "Cancel or remove appointments",
                            Group = "Appointments",
                            Name = "Delete Appointments"
                        },
                        new
                        {
                            Id = new Guid("8b825d03-711b-92c8-9d04-999b294a318c"),
                            Code = "appointments.confirm",
                            Description = "Confirm scheduled appointments",
                            Group = "Appointments",
                            Name = "Confirm Appointments"
                        },
                        new
                        {
                            Id = new Guid("88074e00-d501-1516-74f1-359b42bb70b5"),
                            Code = "reports.create",
                            Description = "Generate new radiology reports",
                            Group = "Reports",
                            Name = "Create Reports"
                        },
                        new
                        {
                            Id = new Guid("121e49c3-044e-461a-62be-f488d70e32a5"),
                            Code = "reports.read",
                            Description = "View radiology reports",
                            Group = "Reports",
                            Name = "Read Reports"
                        },
                        new
                        {
                            Id = new Guid("afb3c764-ed7b-76fb-d661-bb52f1632f24"),
                            Code = "reports.update",
                            Description = "Modify existing reports",
                            Group = "Reports",
                            Name = "Update Reports"
                        },
                        new
                        {
                            Id = new Guid("a9b6b892-9cbf-5e0d-524e-342037a9c0db"),
                            Code = "reports.delete",
                            Description = "Remove reports",
                            Group = "Reports",
                            Name = "Delete Reports"
                        },
                        new
                        {
                            Id = new Guid("4cdd0e15-99f2-163d-bf02-7f9c7085639b"),
                            Code = "reports.export",
                            Description = "Export reports to external formats",
                            Group = "Reports",
                            Name = "Export Reports"
                        },
                        new
                        {
                            Id = new Guid("5e7b27cf-8d84-9117-ace6-bf62930c0d6b"),
                            Code = "users.create",
                            Description = "Create new user accounts",
                            Group = "Identity",
                            Name = "Create Users"
                        },
                        new
                        {
                            Id = new Guid("39599987-0f11-0d0a-d879-7cbd0644220f"),
                            Code = "users.read",
                            Description = "View user accounts",
                            Group = "Identity",
                            Name = "Read Users"
                        },
                        new
                        {
                            Id = new Guid("9357da48-43eb-8b5a-08e1-2970f32cd4e4"),
                            Code = "users.update",
                            Description = "Modify user accounts",
                            Group = "Identity",
                            Name = "Update Users"
                        },
                        new
                        {
                            Id = new Guid("4f1937b2-d2ab-81d3-231f-fd3f82eaeee9"),
                            Code = "users.delete",
                            Description = "Remove user accounts",
                            Group = "Identity",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = new Guid("34aefeb7-996c-2279-4a5f-a07ee459a73d"),
                            Code = "users.manage-roles",
                            Description = "Assign or remove roles from users",
                            Group = "Identity",
                            Name = "Manage User Roles"
                        },
                        new
                        {
                            Id = new Guid("75a5654b-9b89-dd90-0386-c2bf38eb1fa7"),
                            Code = "roles.create",
                            Description = "Create new roles",
                            Group = "Identity",
                            Name = "Create Roles"
                        },
                        new
                        {
                            Id = new Guid("5ca0bded-ae70-5972-59c3-7541f4dae0c5"),
                            Code = "roles.read",
                            Description = "View roles",
                            Group = "Identity",
                            Name = "Read Roles"
                        },
                        new
                        {
                            Id = new Guid("3bcb99ff-db6c-7983-9afd-e23a514b8d87"),
                            Code = "roles.update",
                            Description = "Modify role details",
                            Group = "Identity",
                            Name = "Update Roles"
                        },
                        new
                        {
                            Id = new Guid("8e5a0684-bcd2-8840-b701-2312fcb7ecfa"),
                            Code = "roles.delete",
                            Description = "Remove roles",
                            Group = "Identity",
                            Name = "Delete Roles"
                        },
                        new
                        {
                            Id = new Guid("e66a4a79-01e6-8e89-c8c5-d0ce5044fa01"),
                            Code = "roles.manage-permissions",
                            Description = "Assign or remove permissions from roles",
                            Group = "Identity",
                            Name = "Manage Role Permissions"
                        },
                        new
                        {
                            Id = new Guid("0c592871-6663-c321-024b-f782e8aa258f"),
                            Code = "settings.read",
                            Description = "View system settings",
                            Group = "Settings",
                            Name = "Read Settings"
                        },
                        new
                        {
                            Id = new Guid("e0548f02-0b69-0aa7-d0c3-6b4f5b7a69dd"),
                            Code = "settings.update",
                            Description = "Modify system settings",
                            Group = "Settings",
                            Name = "Update Settings"
                        });
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", "Identity");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "Identity");
                });

            modelBuilder.Entity("AspNetUserRoles", b =>
                {
                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("AssignedRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RadiologyCenter.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsMany("RadiologyCenter.Identity.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Token")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("datetime2");

                            b1.HasKey("UserId", "Token");

                            b1.ToTable("RefreshToken", "Identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiologyCenter.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
