global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using RadiologyCenter.BuildingBlocks.Application.Abstractions;
global using RadiologyCenter.BuildingBlocks.Domain.Results;
global using RadiologyCenter.Cash.Domain.Entities;
global using RadiologyCenter.Cash.Domain.Enumerations;