namespace RadiologyCenter.Desktop.Components;

public record RadiologyStudy(
    string Id,
    string PatientName,
    string PatientCode,
    int Age,
    string Gender,
    string Modality,
    string BodyPart,
    string Priority,
    string Status,
    string ExamName,
    string Indication,
    string ScheduledLabel,
    string Radiologist,
    string Findings,
    string Impression,
    string Recommendation);

public static class RadiologySampleData
{
    public static IReadOnlyList<RadiologyStudy> Studies { get; } = new List<RadiologyStudy>
    {
        new(
            Id: "STU-1001",
            PatientName: "Sameh Gouda",
            PatientCode: "PT-4821",
            Age: 54,
            Gender: "Male",
            Modality: "CT",
            BodyPart: "Chest",
            Priority: "Urgent",
            Status: "InProgress",
            ExamName: "CT Chest (Contrast)",
            Indication: "Persistent cough and chest pain for 3 weeks, rule out pulmonary embolism.",
            ScheduledLabel: "2026-08-05 09:15",
            Radiologist: "Dr. Youssef Mahmoud",
            Findings: string.Empty,
            Impression: string.Empty,
            Recommendation: string.Empty),
        new(
            Id: "STU-1002",
            PatientName: "Mariam Hassan",
            PatientCode: "PT-4788",
            Age: 41,
            Gender: "Female",
            Modality: "MRI",
            BodyPart: "Brain",
            Priority: "Routine",
            Status: "Draft",
            ExamName: "MRI Brain (3T)",
            Indication: "Recurrent headaches, assess for demyelinating lesions.",
            ScheduledLabel: "2026-08-05 10:00",
            Radiologist: "Dr. Sara Ali",
            Findings: "Normal sized lateral and third ventricles. No midline shift. Scattered small T2 hyperintense foci in the periventricular white matter, nonspecific.",
            Impression: "No acute intracranial abnormality. White matter foci are nonspecific, possibly chronic microvascular change.",
            Recommendation: "Clinical correlation advised. Consider follow-up MRI if symptoms worsen."),
        new(
            Id: "STU-1003",
            PatientName: "Adam Kareem",
            PatientCode: "PT-4791",
            Age: 23,
            Gender: "Male",
            Modality: "X-Ray",
            BodyPart: "Right Hand",
            Priority: "Routine",
            Status: "InProgress",
            ExamName: "X-Ray Right Hand (AP/Lat)",
            Indication: "Trauma to right hand, assess for fracture.",
            ScheduledLabel: "2026-08-05 11:30",
            Radiologist: "Dr. Karim Hassan",
            Findings: string.Empty,
            Impression: string.Empty,
            Recommendation: string.Empty),
        new(
            Id: "STU-1004",
            PatientName: "Salma Ezzat",
            PatientCode: "PT-4760",
            Age: 35,
            Gender: "Female",
            Modality: "Ultrasound",
            BodyPart: "Abdomen",
            Priority: "Stat",
            Status: "InProgress",
            ExamName: "Ultrasound Abdomen (Full)",
            Indication: "Acute right upper quadrant pain, assess gallbladder and liver.",
            ScheduledLabel: "2026-08-05 12:00",
            Radiologist: "Dr. Nour El-Din",
            Findings: string.Empty,
            Impression: string.Empty,
            Recommendation: string.Empty),
        new(
            Id: "STU-1005",
            PatientName: "Omar Shehata",
            PatientCode: "PT-4752",
            Age: 68,
            Gender: "Male",
            Modality: "CT",
            BodyPart: "Head",
            Priority: "Routine",
            Status: "Completed",
            ExamName: "CT Head (Non-contrast)",
            Indication: "Mild cognitive decline, assess cerebral atrophy and white matter change.",
            ScheduledLabel: "2026-08-04 16:45",
            Radiologist: "Dr. Youssef Mahmoud",
            Findings: "Mild global cerebral atrophy disproportionate to age. Periventricular white matter changes. No hemorrhage, mass, or acute infarct.",
            Impression: "Age-related cerebral atrophy with mild chronic small vessel disease.",
            Recommendation: "No further imaging indicated at this time. Clinical follow-up."),
    };
}