<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
    <PackageReference Include="WolverineFx" Version="6.24.0" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.24.0" />
    <PackageReference Include="WolverineFx.FluentValidation" Version="6.24.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.24.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\RadiologyCenter.BuildingBlocks.Application\RadiologyCenter.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\RadiologyCenter.BuildingBlocks.Infrastructure\RadiologyCenter.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\RadiologyCenter.Idnetity.Application\RadiologyCenter.Idnetity.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\RadiologyCenter.Idnetity.Infrastructure\RadiologyCenter.Idnetity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
