<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Localhost\RadiologyCenter.Localhost\RadiologyCenter.Localhost.csproj" />
  </ItemGroup>

</Project>
